version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  ecoleta-server:
    container_name: ecoleta-server
    build: 
      dockerfile: ./server/Dockerfile
      context: .
    image: jorgedjr21/ecoleta-server
    command: sh -c "npm run dev"
    volumes:
      - ./server/:/ecoleta-server
    ports:
      - "3000:3333"
    depends_on:
      - db

volumes:
  postgres-data: