version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  ecoleta-server:
    container_name: ecoleta-server
    build: 
      dockerfile: ./server/Dockerfile
      context: .
    image: jorgedjr21/ecoleta-server
    command: sh -c "npm run dev"
    volumes:
      - ./server/:/ecoleta-server
    ports:
      - "3001:3333"
    depends_on:
      - db
  ecoleta-web:
    container_name: ecoleta-web
    stdin_open: true
    build:
      dockerfile: ./web/Dockerfile
      context: .
    image: jorgedjr21/ecoleta-web
    command: sh -c "npm run start"
    volumes:
      - ./web/:/ecoleta-web
    ports:
      - "3000:3000"
    depends_on:
      - ecoleta-server

volumes:
  postgres-data: